
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Django 3.2
          - django-version: "3.2.0"
            python-version: "3.6"
          - django-version: "3.2.0"
            python-version: "3.7"
          - django-version: "3.2.0"
            python-version: "3.8"
          - django-version: "3.2.0"
            python-version: "3.9"
          - django-version: "3.2.0"
            python-version: "3.10"

          # Django 4.0
          - django-version: "4.0.0"
            python-version: "3.8"
          - django-version: "4.0.0"
            python-version: "3.9"
          - django-version: "4.0.0"
          python-version: "3.10"

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip version
        run: python -m pip install -U pip

      - name: Upgrade django version
        run: python -m pip install "Django~=${{ matrix.django-version }}"

      - name: Python and Django versions
        run: |
          echo "Python ${{ matrix.python-version }} -> Django ${{ matrix.django-version }}"
          python --version
          echo "Django: `django-admin --version`"

      - name: Run Tests
        run: |
          python manage.py test